# Generated by Django 4.1.5 on 2023-06-21 23:54

from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
import tinymce.models
import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="blog_authors", verbose_name="Image"),
                ),
                ("designation", models.CharField(max_length=255, verbose_name="Designation")),
            ],
            options={"verbose_name": "Blog Author", "verbose_name_plural": "Blog Authors"},
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("address", models.TextField(verbose_name="Address")),
                ("phone", models.CharField(max_length=255, verbose_name="Phone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
            options={"verbose_name": "Branch", "verbose_name_plural": "Branches"},
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email")),
                ("phone", models.CharField(max_length=255, verbose_name="Phone")),
                ("message", models.TextField(verbose_name="Message")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Timestamp")),
            ],
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="destinations", verbose_name="Image"),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
            ],
            options={"verbose_name": "Destination", "verbose_name_plural": "Destinations"},
        ),
        migrations.CreateModel(
            name="FixedDeparture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("destination", models.CharField(max_length=255, verbose_name="Destination")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("departure_from", models.CharField(max_length=255, verbose_name="Departure From")),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="fixed_departures", verbose_name="Image"),
                ),
                ("duration", models.CharField(max_length=255, verbose_name="Duration")),
                ("date", models.DateField(verbose_name="Date")),
                ("total_seats", models.PositiveIntegerField(verbose_name="Total Seats")),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("AED", "United Arab Emirates Dirham"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                ("price", djmoney.models.fields.MoneyField(decimal_places=2, default_currency="INR", max_digits=14)),
                (
                    "advance_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("AED", "United Arab Emirates Dirham"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "advance",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), default_currency="INR", max_digits=14
                    ),
                ),
                ("available_until", models.DateField(verbose_name="Available Until")),
                ("rating", models.SmallIntegerField(default=5, verbose_name="Rating")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "adult_costing_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("AED", "United Arab Emirates Dirham"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "adult_costing",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), default_currency="INR", max_digits=14
                    ),
                ),
                (
                    "child_with_bed_costing_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("AED", "United Arab Emirates Dirham"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "child_with_bed_costing",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), default_currency="INR", max_digits=14
                    ),
                ),
                (
                    "child_without_bed_costing_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("AED", "United Arab Emirates Dirham"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "child_without_bed_costing",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), default_currency="INR", max_digits=14
                    ),
                ),
                (
                    "infant_costing_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("AED", "United Arab Emirates Dirham"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "infant_costing",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), default_currency="INR", max_digits=14
                    ),
                ),
                (
                    "single_occupancy_costing_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("AED", "United Arab Emirates Dirham"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "single_occupancy_costing",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), default_currency="INR", max_digits=14
                    ),
                ),
                (
                    "payment_terms",
                    tinymce.models.HTMLField(
                        default='<p><strong>For customization&nbsp;packages without Flights:<br /></strong></p><table style="font-weight: 400;"><tbody><tr><td><strong>Payment Procedure Minimum Per Person Payment to be made by the client*</strong></td><td><strong>Charges</strong></td></tr><tr><td>At the time of booking</td><td><p>INR 15,000/- per person</p></td></tr><tr><td>Within 31 - 45 days prior to the date of departure</td><td>75% of the holiday cost</td></tr><tr><td>Less than 30 &amp; below from the date of departure</td><td>100% of the holiday cost</td></tr></tbody></table><p style="font-weight: 400;"><u><br /></u><strong>For customization&nbsp;packages inclusive of Flights:<br /></strong></p><table style="font-weight: 400;"><tbody><tr><td><strong>Payment Procedure Minimum Per Person Payment to be made by the client*</strong></td><td><strong>Charges</strong></td></tr><tr><td>At the time of booking</td><td>Full Payments towards Air Tickets +&nbsp;Defined Minimum Booking Deposit / 10% Payment Towards Land Package</td></tr><tr><td>Within 31 - 45 days prior to the date of departure</td><td>75% of the holiday cost</td></tr><tr><td>Less than 30 &amp; below from the date of departure</td><td>100% of the holiday cost</td></tr></tbody></table><p><strong>Notes:<br /></strong></p><ul><li>If you are booking a non-refundable and time-limit itinerary, you will need to pay 100% of the cost to confirm your booking. All payments must be made to the company in accordance with the procedure and time frame outlined below.</li><li>If you are booking air tickets that are being issued or blocked on a time limit, the full Indian Rupee (INR) amount will need to be collected before issuance. If payment is not made before the time limit, the price may be subject to change.</li><li>An initial booking deposit will be collected based on the amount mentioned or the package price, whichever is lower. Full payment must be made according to the procedure outlined above.</li><li>If you fail to comply with the payment procedures, the company reserves the right to cancel your tour/booking, with subsequent loss of deposit, and to apply and recover the cancellation charges as mentioned.</li></ul>',
                        verbose_name="Payment Terms",
                    ),
                ),
                (
                    "cancellation_policy",
                    tinymce.models.HTMLField(
                        default='<p style="font-weight: 400;"><strong>For Customization packages:<br /></strong></p><table style="font-weight: 400;"><tbody><tr><td><strong>When a Cancellation is made</strong></td><td><strong>Charges</strong></td></tr><tr><td>Prior to 46 days from the date of departure</td><td>Non-Refundable Booking Deposit</td></tr><tr><td>Between 45 - 31 days from the date of departure</td><td>75% of the holiday cost</td></tr><tr><td>Between 30 or below from the date of departure</td><td>100% of the holiday cost</td></tr></tbody></table><p>When you book services for a tour in advance, cancelling those services closer to the departure date causes the company to lose money with the supplier. So, if you cancel your tour or services, the company will charge a cancellation fee as specified. If you book any third-party product or service, their terms and conditions will apply in addition to the company\'s terms and conditions. If you cancel, you must do so in writing and state the reasons for cancellation. By booking, you agree to these terms.</p><p>The company may cancel a tour before departure without giving any reason. If this happens, the company will refund all the money you paid in Indian Rupees, but you won\'t receive any compensation. The company is not responsible for any additional costs or fees related to air tickets or other arrangements that were not booked through the company.</p><p style="font-weight: 400;"><strong>Notes:</strong></p><ol style="font-weight: 400;"><li>The above is a general cancellation policy and the same is subject to change depending on the travel date, the destination, the package and the services booked and paid for.</li><li>For Dynamic properties and Reconfirmed Bookings, the above Cancellation may not be applicable and could vary.</li></ol>',
                        verbose_name="Cancellation Policy",
                    ),
                ),
                (
                    "terms_and_conditions",
                    tinymce.models.HTMLField(
                        default='<p>For more detailed terms and conditions, please refer to the following page:&nbsp; <a href="https://skydays.travel/terms_and_conditions/" target="_new">https://skydays.travel/terms_and_conditions/</a>.</p>',
                        verbose_name="Terms and Conditions",
                    ),
                ),
                (
                    "overview",
                    tinymce.models.HTMLField(
                        default="<h3>Highlights</h3><ul><li>Coral Island Tour in Pattaya with Indian Lunch</li><li>One cup of Tea and 1 samosa at Coral island</li><li>1 Hour Thai Traditional Message (Only Adult)</li><li>Entry Ticket for Art in Paradise in Pattaya (Transfers on own)</li><li>Bangkok City tour with Golden and Marble Buddha Temple</li><li>Complimentary 1 Water bottle every day</li><li>Buy One Get One Free (BOGO) offer is only valid for 2 adults - Pay for one and your adult companion travels FREE!</li><li>Covid Travel Insurance covering Hotel/ Institutional Quarantine stay expenses in case customer tests positive on tour (upto a maximum of $ 3000¹)</li></ul><h4>Meals</h4><ul><li>Indian lunch during Coral Island Tour</li><li>Daily Breakfast (Except day-1)</li></ul><h4>What your tour price includes?</h4><ul><li><strong>Accommodation:</strong> 02 night’s accommodation in Pattaya02 night’s accommodation in Bangkok </li><li><strong>Transfers:</strong> Transfer from Bangkok Airport to Pattaya Hotel & Bangkok Hotel to Bangkok Airport on Seat In Coach transfer basis.Transfer from Pattaya Hotel to Bangkok Hotel on Seat In Coach transfer basis.</li><li><strong>Sightseeing:</strong> Pattaya Coral Island TourEntry Ticket for Art in ParadiseBangkok City tour with Golden and Marble Buddha temple on seat in coach basis (Gems Gallery is not visited)</li><li><strong>Insurance:</strong> Travel Insurance - Valid for 7 days up to the age of 60 years with the coverage of USD 100,000 (Excluding US & Canada)</li><li><strong>Others:</strong> 1 Water bottle every day</li></ul><h4>What your tour price does not include?</h4><ul><li>GST and TCS as applicable</li><li>Thailand Visa Charges (visa on arrival charges are approx THB 2000 per person - subject to change)</li><li>Guaranteed early check in or late check out. This is completely at the discretion of the hotel and we can only put in a request for the same.</li><li>Tips and porter-age</li><li>Meals other than that what is mentioned in your itinerary.</li><li>Drinks including Water during meals / sightseeing tours are not included</li><li>Any expenses of personal nature</li><li>Surcharges as applicable due to peak season, surcharge dates, trade fair dates, any block out dates</li><li>Any services not mentioned in the inclusions list</li></ul>",
                        verbose_name="Overview",
                    ),
                ),
                (
                    "itinerary",
                    tinymce.models.HTMLField(
                        default='<div class="p-timeline-overview"><h4>Overview</h4><p>Pellentesque accumsan magna in augue sagittis, non fringilla eros molestie. Sed feugiat mi nec ex vehicula, nec vestibulum orci semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tristique commodo fringilla. Duis aliquet varius mauris eget rutrum. Nullam sit amet justo consequat, bibendum orci in, convallis enim. Proin convallis neque viverra finibus cursus. Mauris lacinia lacinia erat in finibus.</p></div><h4>&nbsp;</h4><h4>DAY 1 : Departure And Small Tour</h4><h6><em><strong>10.00 AM to 10.00 PM</strong></em></h6><p>Pellentesque accumsan magna in augue sagittis, non fringilla eros molestie. Sed feugiat mi nec ex vehicula, nec vestibulum orci semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tristique commodo fringilla.</p><ul><li>Specilaized Bilingual Guide</li><li>Private Transport</li><li>Entrance Fees</li><li>Box Lunch,Water,Dinner and Snacks</li></ul><div class="timeline-index"><div class="index-circle"><h4>&nbsp;</h4><h4>DAY 2 : Departure And Small Tour</h4></div></div><div class="timeline-content"><h6><em><strong>10.00 AM to 10.00 PM</strong></em></h6><p>Pellentesque accumsan magna in augue sagittis, non fringilla eros molestie. Sed feugiat mi nec ex vehicula, nec vestibulum orci semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tristique commodo fringilla.</p><ul><li>Specilaized Bilingual Guide</li><li>Private Transport</li><li>Entrance Fees</li><li>Box Lunch,Water,Dinner and Snacks</li></ul></div>',
                        verbose_name="Itinerary",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="fixed_departures", verbose_name="Attachment"),
                ),
            ],
            options={"verbose_name": "Fixed Departure", "verbose_name_plural": "Fixed Departures"},
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("destination", models.CharField(max_length=255, verbose_name="Destination")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("departure_from", models.CharField(max_length=255, verbose_name="Departure From")),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(upload_to="fixed_departures", verbose_name="Image"),
                ),
                ("duration", models.CharField(max_length=255, verbose_name="Duration")),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("AED", "United Arab Emirates Dirham"),
                        ],
                        default="INR",
                        editable=False,
                        max_length=3,
                    ),
                ),
                ("price", djmoney.models.fields.MoneyField(decimal_places=2, default_currency="INR", max_digits=14)),
                ("available_until", models.DateField(verbose_name="Available Until")),
                ("rating", models.SmallIntegerField(default=5, verbose_name="Rating")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_bestplace", models.BooleanField(default=True, verbose_name="Mark as Best Place")),
                ("is_special", models.BooleanField(default=True, verbose_name="Mark as Special Deal")),
                (
                    "payment_terms",
                    tinymce.models.HTMLField(
                        default='<p><strong>For customization&nbsp;packages without Flights:<br /></strong></p><table style="font-weight: 400;"><tbody><tr><td><strong>Payment Procedure Minimum Per Person Payment to be made by the client*</strong></td><td><strong>Charges</strong></td></tr><tr><td>At the time of booking</td><td><p>INR 15,000/- per person</p></td></tr><tr><td>Within 31 - 45 days prior to the date of departure</td><td>75% of the holiday cost</td></tr><tr><td>Less than 30 &amp; below from the date of departure</td><td>100% of the holiday cost</td></tr></tbody></table><p style="font-weight: 400;"><u><br /></u><strong>For customization&nbsp;packages inclusive of Flights:<br /></strong></p><table style="font-weight: 400;"><tbody><tr><td><strong>Payment Procedure Minimum Per Person Payment to be made by the client*</strong></td><td><strong>Charges</strong></td></tr><tr><td>At the time of booking</td><td>Full Payments towards Air Tickets +&nbsp;Defined Minimum Booking Deposit / 10% Payment Towards Land Package</td></tr><tr><td>Within 31 - 45 days prior to the date of departure</td><td>75% of the holiday cost</td></tr><tr><td>Less than 30 &amp; below from the date of departure</td><td>100% of the holiday cost</td></tr></tbody></table><p><strong>Notes:<br /></strong></p><ul><li>If you are booking a non-refundable and time-limit itinerary, you will need to pay 100% of the cost to confirm your booking. All payments must be made to the company in accordance with the procedure and time frame outlined below.</li><li>If you are booking air tickets that are being issued or blocked on a time limit, the full Indian Rupee (INR) amount will need to be collected before issuance. If payment is not made before the time limit, the price may be subject to change.</li><li>An initial booking deposit will be collected based on the amount mentioned or the package price, whichever is lower. Full payment must be made according to the procedure outlined above.</li><li>If you fail to comply with the payment procedures, the company reserves the right to cancel your tour/booking, with subsequent loss of deposit, and to apply and recover the cancellation charges as mentioned.</li></ul>',
                        verbose_name="Payment Terms",
                    ),
                ),
                (
                    "cancellation_policy",
                    tinymce.models.HTMLField(
                        default='<p style="font-weight: 400;"><strong>For Customization packages:<br /></strong></p><table style="font-weight: 400;"><tbody><tr><td><strong>When a Cancellation is made</strong></td><td><strong>Charges</strong></td></tr><tr><td>Prior to 46 days from the date of departure</td><td>Non-Refundable Booking Deposit</td></tr><tr><td>Between 45 - 31 days from the date of departure</td><td>75% of the holiday cost</td></tr><tr><td>Between 30 or below from the date of departure</td><td>100% of the holiday cost</td></tr></tbody></table><p>When you book services for a tour in advance, cancelling those services closer to the departure date causes the company to lose money with the supplier. So, if you cancel your tour or services, the company will charge a cancellation fee as specified. If you book any third-party product or service, their terms and conditions will apply in addition to the company\'s terms and conditions. If you cancel, you must do so in writing and state the reasons for cancellation. By booking, you agree to these terms.</p><p>The company may cancel a tour before departure without giving any reason. If this happens, the company will refund all the money you paid in Indian Rupees, but you won\'t receive any compensation. The company is not responsible for any additional costs or fees related to air tickets or other arrangements that were not booked through the company.</p><p style="font-weight: 400;"><strong>Notes:</strong></p><ol style="font-weight: 400;"><li>The above is a general cancellation policy and the same is subject to change depending on the travel date, the destination, the package and the services booked and paid for.</li><li>For Dynamic properties and Reconfirmed Bookings, the above Cancellation may not be applicable and could vary.</li></ol>',
                        verbose_name="Cancellation Policy",
                    ),
                ),
                (
                    "terms_and_conditions",
                    tinymce.models.HTMLField(
                        default='<p>For more detailed terms and conditions, please refer to the following page:&nbsp; <a href="https://skydays.travel/terms_and_conditions/" target="_new">https://skydays.travel/terms_and_conditions/</a>.</p>',
                        verbose_name="Terms and Conditions",
                    ),
                ),
                (
                    "overview",
                    tinymce.models.HTMLField(
                        default="<h3>Highlights</h3><ul><li>Coral Island Tour in Pattaya with Indian Lunch</li><li>One cup of Tea and 1 samosa at Coral island</li><li>1 Hour Thai Traditional Message (Only Adult)</li><li>Entry Ticket for Art in Paradise in Pattaya (Transfers on own)</li><li>Bangkok City tour with Golden and Marble Buddha Temple</li><li>Complimentary 1 Water bottle every day</li><li>Buy One Get One Free (BOGO) offer is only valid for 2 adults - Pay for one and your adult companion travels FREE!</li><li>Covid Travel Insurance covering Hotel/ Institutional Quarantine stay expenses in case customer tests positive on tour (upto a maximum of $ 3000¹)</li></ul><h4>Meals</h4><ul><li>Indian lunch during Coral Island Tour</li><li>Daily Breakfast (Except day-1)</li></ul><h4>What your tour price includes?</h4><ul><li><strong>Accommodation:</strong> 02 night’s accommodation in Pattaya02 night’s accommodation in Bangkok </li><li><strong>Transfers:</strong> Transfer from Bangkok Airport to Pattaya Hotel & Bangkok Hotel to Bangkok Airport on Seat In Coach transfer basis.Transfer from Pattaya Hotel to Bangkok Hotel on Seat In Coach transfer basis.</li><li><strong>Sightseeing:</strong> Pattaya Coral Island TourEntry Ticket for Art in ParadiseBangkok City tour with Golden and Marble Buddha temple on seat in coach basis (Gems Gallery is not visited)</li><li><strong>Insurance:</strong> Travel Insurance - Valid for 7 days up to the age of 60 years with the coverage of USD 100,000 (Excluding US & Canada)</li><li><strong>Others:</strong> 1 Water bottle every day</li></ul><h4>What your tour price does not include?</h4><ul><li>GST and TCS as applicable</li><li>Thailand Visa Charges (visa on arrival charges are approx THB 2000 per person - subject to change)</li><li>Guaranteed early check in or late check out. This is completely at the discretion of the hotel and we can only put in a request for the same.</li><li>Tips and porter-age</li><li>Meals other than that what is mentioned in your itinerary.</li><li>Drinks including Water during meals / sightseeing tours are not included</li><li>Any expenses of personal nature</li><li>Surcharges as applicable due to peak season, surcharge dates, trade fair dates, any block out dates</li><li>Any services not mentioned in the inclusions list</li></ul>",
                        verbose_name="Overview",
                    ),
                ),
                (
                    "itinerary",
                    tinymce.models.HTMLField(
                        default='<div class="p-timeline-overview"><h4>Overview</h4><p>Pellentesque accumsan magna in augue sagittis, non fringilla eros molestie. Sed feugiat mi nec ex vehicula, nec vestibulum orci semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tristique commodo fringilla. Duis aliquet varius mauris eget rutrum. Nullam sit amet justo consequat, bibendum orci in, convallis enim. Proin convallis neque viverra finibus cursus. Mauris lacinia lacinia erat in finibus.</p></div><h4>&nbsp;</h4><h4>DAY 1 : Departure And Small Tour</h4><h6><em><strong>10.00 AM to 10.00 PM</strong></em></h6><p>Pellentesque accumsan magna in augue sagittis, non fringilla eros molestie. Sed feugiat mi nec ex vehicula, nec vestibulum orci semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tristique commodo fringilla.</p><ul><li>Specilaized Bilingual Guide</li><li>Private Transport</li><li>Entrance Fees</li><li>Box Lunch,Water,Dinner and Snacks</li></ul><div class="timeline-index"><div class="index-circle"><h4>&nbsp;</h4><h4>DAY 2 : Departure And Small Tour</h4></div></div><div class="timeline-content"><h6><em><strong>10.00 AM to 10.00 PM</strong></em></h6><p>Pellentesque accumsan magna in augue sagittis, non fringilla eros molestie. Sed feugiat mi nec ex vehicula, nec vestibulum orci semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tristique commodo fringilla.</p><ul><li>Specilaized Bilingual Guide</li><li>Private Transport</li><li>Entrance Fees</li><li>Box Lunch,Water,Dinner and Snacks</li></ul></div>',
                        verbose_name="Itinerary",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="fixed_departures", verbose_name="Attachment"),
                ),
            ],
            options={"verbose_name": "Package", "verbose_name_plural": "Packages"},
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("image", versatileimagefield.fields.VersatileImageField(upload_to="reviews", verbose_name="Image")),
                ("review", models.TextField(verbose_name="Review")),
                ("rating", models.SmallIntegerField(default=5, verbose_name="Rating")),
            ],
            options={"verbose_name": "Review", "verbose_name_plural": "Reviews"},
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("image", versatileimagefield.fields.VersatileImageField(upload_to="team", verbose_name="Image")),
                ("designation", models.CharField(max_length=255, verbose_name="Designation")),
            ],
            options={"verbose_name": "Team Member", "verbose_name_plural": "Team Members"},
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("video_id", models.CharField(max_length=255, verbose_name="Video ID")),
                (
                    "thumbnail",
                    versatileimagefield.fields.VersatileImageField(upload_to="videos", verbose_name="Thumbnail"),
                ),
            ],
            options={"verbose_name": "Video", "verbose_name_plural": "Videos"},
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", versatileimagefield.fields.VersatileImageField(upload_to="gallery", verbose_name="Image")),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="web.destination",
                    ),
                ),
            ],
            options={"verbose_name": "Gallery Image", "verbose_name_plural": "Gallery Images"},
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("image", versatileimagefield.fields.VersatileImageField(upload_to="blogs", verbose_name="Image")),
                ("summary", models.TextField(verbose_name="Summary")),
                ("date", models.DateField(verbose_name="Date")),
                ("tag", models.CharField(max_length=255, verbose_name="Tag")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_popular", models.BooleanField(default=True, verbose_name="Mark as Popular")),
                ("content", tinymce.models.HTMLField(verbose_name="Content")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="Views")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="web.blogauthor",
                        verbose_name="Author",
                    ),
                ),
            ],
            options={"verbose_name": "Blog", "verbose_name_plural": "Blogs"},
        ),
    ]
