# Generated by Django 4.1.5 on 2023-06-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("web", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="fixeddeparture", name="advance"),
        migrations.RemoveField(model_name="fixeddeparture", name="advance_currency"),
    ]
