# Generated by Django 4.1.5 on 2024-04-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("web", "0002_remove_fixeddeparture_advance_and_more")]

    operations = [
        migrations.AlterModelOptions(name="blog", options={"ordering": ("-date",), "verbose_name": "Blog", "verbose_name_plural": "Blogs"}),
        migrations.AlterModelOptions(name="branch", options={"ordering": ("-priority",), "verbose_name": "Branch", "verbose_name_plural": "Branches"}),
        migrations.AlterModelOptions(name="contact", options={"ordering": ("name",), "verbose_name": "Contact", "verbose_name_plural": "Contacts"}),
        migrations.AlterModelOptions(
            name="fixeddeparture", options={"ordering": ("-date",), "verbose_name": "Fixed Departure", "verbose_name_plural": "Fixed Departures"}
        ),
        migrations.AddField(model_name="branch", name="priority", field=models.SmallIntegerField(default=1)),
    ]
