# Generated by Django 4.1.5 on 2024-08-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("web", "0003_alter_blog_options_alter_branch_options_and_more")]

    operations = [
        migrations.AlterModelOptions(name="blog", options={"ordering": ("date",), "verbose_name": "Blog", "verbose_name_plural": "Blogs"}),
        migrations.AlterModelOptions(name="fixeddeparture", options={"ordering": ("date",), "verbose_name": "Fixed Departure", "verbose_name_plural": "Fixed Departures"}),
        migrations.AddField(model_name="fixeddeparture", name="is_sold_out", field=models.BooleanField(default=False, verbose_name="Marked as Sold Out")),
    ]
