# Generated by Django 4.1.5 on 2025-01-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("web", "0004_alter_blog_options_alter_fixeddeparture_options_and_more")]

    operations = [
        migrations.RemoveField(model_name="fixeddeparture", name="itinerary"),
        migrations.RemoveField(model_name="package", name="itinerary"),
        migrations.AddField(model_name="fixeddeparture", name="brochure", field=models.FileField(blank=True, null=True, upload_to="fixed_departures", verbose_name="Brochure")),
        migrations.AddField(model_name="package", name="brochure", field=models.FileField(blank=True, null=True, upload_to="fixed_departures", verbose_name="Brochure")),
        migrations.AlterField(model_name="package", name="is_special", field=models.BooleanField(default=False, verbose_name="Mark as Special Deal")),
    ]
