# Generated by Django 4.1.5 on 2025-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("web", "0005_remove_fixeddeparture_itinerary_and_more")]

    operations = [
        migrations.AddField(
            model_name="fixeddeparture", name="available_seats", field=models.PositiveIntegerField(default=0, verbose_name="Available Seats"), preserve_default=False
        )
    ]
