# Generated by Django 4.0.1 on 2022-01-18 21:17

import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("products", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=128, null=True)),
                ("phone", models.CharField(default="+91 0000 000 000", max_length=128)),
                ("description", models.TextField()),
                ("address", models.TextField()),
            ],
            options={"verbose_name": "About", "verbose_name_plural": "About"},
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/banners", verbose_name="Banner Photo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("title",)},
        ),
        migrations.CreateModel(
            name="CareerPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "featured_image",
                    versatileimagefield.fields.VersatileImageField(upload_to="images/careers/featured_image/"),
                ),
                ("content", tinymce.models.HTMLField()),
                ("timestamp", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                (
                    "logo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/clients", verbose_name="Photo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                ("place", models.CharField(blank=True, max_length=120, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "featured_image",
                    versatileimagefield.fields.VersatileImageField(upload_to="images/blog/featured_image/"),
                ),
                ("summary", models.TextField()),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "News", "verbose_name_plural": "News & Updates"},
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.IntegerField(unique=True)),
                ("media", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Social Media", "verbose_name_plural": "Social Medias", "ordering": ("order",)},
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("content", models.TextField()),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images/testimonials", verbose_name="Photo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                ("place", models.CharField(blank=True, max_length=120, null=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
            options={"verbose_name": "Product Enquiry", "verbose_name_plural": "Product Enquiries"},
        ),
        migrations.CreateModel(
            name="CareerApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                ("place", models.CharField(blank=True, max_length=120, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("resume", models.FileField(upload_to="docs/careers/applications/")),
                ("career", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.careerpost")),
            ],
        ),
    ]
