# Generated by Django 4.0.2 on 2022-04-22 05:38

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("web", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(name="careerpost", options={"ordering": ["-pub_date"]}),
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-pub_date"], "verbose_name": "News", "verbose_name_plural": "News & Updates"},
        ),
        migrations.AddField(
            model_name="careerpost",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
