# Generated by Django 4.2.9 on 2026-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_careerpost_options_alter_news_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
