# Generated by Django 4.0.5 on 2022-11-13 18:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Property Management", "Property Management"),
                            ("Mortgage Service", "Mortgage Service"),
                            ("Consulting Service", "Consulting Service"),
                            ("Home Buying", "Home Buying"),
                            ("Home Selling", "Home Selling"),
                            ("Escrow Services", "Escrow Services"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name_plural": "Enquiries"},
        )
    ]
