# Generated by Django 4.2.9 on 2025-01-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndustryExpert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="industry_expert_logo")),
            ],
        ),
    ]
