# Generated by Django 4.2.9 on 2025-01-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industryexpert",
            options={"ordering": ("priority",), "verbose_name": "Industry Expert", "verbose_name_plural": "Industry Experts"},
        ),
        migrations.AddField(
            model_name="industryexpert",
            name="priority",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
