# Generated by Django 4.2.9 on 2025-01-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_industryexpert_options_industryexpert_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("icon", models.FileField(help_text="SVG file 30x30", upload_to="skill_category_icon")),
            ],
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
                "ordering": ("priority",),
            },
        ),
    ]
