# Generated by Django 4.2.9 on 2025-01-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_skillcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skillcategory",
            options={"verbose_name": "Skill Category", "verbose_name_plural": "Skill Categories"},
        ),
        migrations.RemoveField(
            model_name="skillcategory",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="skillcategory",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="skillcategory",
            name="subtitle",
        ),
        migrations.AlterField(
            model_name="skillcategory",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="course_image")),
                ("skill_category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.skillcategory")),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ("title",),
            },
        ),
    ]
