# Generated by Django 4.2.9 on 2025-01-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_faq_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillcategory",
            name="icon",
            field=models.FileField(default=1, upload_to="skill_category_icon"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skillcategory",
            name="subtitle",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
