# Generated by Django 4.2.9 on 2025-01-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_application_chatrequest_phonerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="summary",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
