# Generated by Django 4.2.9 on 2025-01-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_course_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="chatrequest",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="phonerequest",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
