# Generated by Django 4.2.9 on 2025-01-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_alter_application_phone_alter_chatrequest_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
