# Generated by Django 4.2.9 on 2025-03-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_event_registration_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(max_length=20)),
                ("message", models.TextField(verbose_name="Why do you want to join this course?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.course")),
            ],
            options={
                "verbose_name": "Course Enquiry",
                "verbose_name_plural": "Course Enquiries",
                "ordering": ("-created_at",),
            },
        ),
    ]
