# Generated by Django 4.1.5 on 2023-06-21 23:54

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("web", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Airport", "verbose_name_plural": "Airports"},
        ),
        migrations.CreateModel(
            name="FixedDepartureEnquiry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("whatsapp", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("ADVANCE", "Pay advance & book your seats"),
                            ("FULL", "Pay full amount"),
                            ("TALK", "Talk with Counselor"),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("departure", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.fixeddeparture")),
            ],
            options={"verbose_name": "Fixed Departure Enquiry", "verbose_name_plural": "Fixed Departure Enquiries"},
        ),
        migrations.CreateModel(
            name="PackageEnquiry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "hotel_category",
                    models.CharField(
                        choices=[
                            ("", "-- Select Hotel Category --"),
                            ("3STAR", "3 Star"),
                            ("4STAR", "4 Star"),
                            ("5STAR", "5 Star"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("whatsapp", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("package", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.package")),
            ],
            options={
                "verbose_name": "Package Enquiry",
                "verbose_name_plural": "Package Enquiries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PackageTraveller",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adult", models.IntegerField()),
                ("child_with_bed", models.IntegerField()),
                ("child_without_bed", models.IntegerField()),
                ("infant", models.IntegerField()),
                (
                    "enquiry",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="enquiry.packageenquiry"),
                ),
            ],
            options={"verbose_name": "Package Enquiry Traveller", "verbose_name_plural": "Package Enquiry Travellers"},
        ),
        migrations.CreateModel(
            name="FixedDepartureTraveller",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        choices=[("MR", "Mr"), ("MRS", "Mrs"), ("MS", "Ms"), ("MISS", "Miss")], max_length=100
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("passport_number", models.CharField(max_length=100)),
                ("passport_expiry", models.DateField()),
                (
                    "meal_preference",
                    models.CharField(choices=[("VEG", "Vegetarian"), ("NONVEG", "Non-Vegetarian")], max_length=100),
                ),
                (
                    "enquiry",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="enquiry.fixeddepartureenquiry"),
                ),
            ],
            options={"verbose_name": "Fixed Departure Traveller", "verbose_name_plural": "Fixed Departure Travellers"},
        ),
        migrations.CreateModel(
            name="CustomPackageEnquiry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=100)),
                ("whatsapp", models.CharField(blank=True, max_length=100, null=True)),
                ("adult", models.IntegerField(default=1, help_text="12+ Yrs")),
                ("child", models.IntegerField(default=0, help_text="Below 12 Yrs")),
                ("infant", models.IntegerField(default=0, help_text="0-2 Yrs")),
                ("travel_date", models.DateField(help_text="Which date you want to travel")),
                (
                    "destination",
                    models.CharField(help_text="Which holiday destination you would like to visit?", max_length=100),
                ),
                ("days", models.IntegerField(default=1, help_text="For how many days")),
                (
                    "preference",
                    models.TextField(blank=True, help_text="Mention any other preferances (if any)", null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "airport",
                    models.ForeignKey(
                        help_text="Which airport you would like to depart from?",
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enquiry.airport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Package Enquiry",
                "verbose_name_plural": "Custom Package Enquiries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
