# Generated by Django 4.1.5 on 2023-06-22 02:28

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("enquiry", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PackageRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("adult", models.IntegerField()),
                ("child_with_bed", models.IntegerField()),
                ("child_without_bed", models.IntegerField()),
                ("infant", models.IntegerField()),
                (
                    "enquiry",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="enquiry.fixeddepartureenquiry"),
                ),
            ],
            options={"verbose_name": "Package Enquiry Room", "verbose_name_plural": "Package Enquiry Rooms"},
        )
    ]
