# Generated by Django 4.1.5 on 2023-06-25 00:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("enquiry", "0002_packageroom")]

    operations = [
        migrations.AddField(
            model_name="fixeddepartureenquiry", name="is_paid", field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name="fixeddepartureenquiry", name="paid_amount", field=models.IntegerField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="fixeddepartureenquiry", name="paid_at", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="fixeddepartureenquiry",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("ADVANCE", "Pay Advance & book seats"),
                    ("FULL", "Pay Full Amount"),
                    ("TALK", "Talk with Counselor"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fixeddeparturetraveller",
            name="meal_preference",
            field=models.CharField(choices=[("VEG", "Veg"), ("NONVEG", "Non-Veg"), ("BOTH", "Both")], max_length=100),
        ),
    ]
