# Generated by Django 4.1.5 on 2023-06-26 10:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("enquiry", "0003_fixeddepartureenquiry_is_paid_and_more")]

    operations = [
        migrations.AddField(
            model_name="packageenquiry", name="order_id", field=models.CharField(blank=True, max_length=128, null=True)
        )
    ]
