# Generated by Django 4.1.5 on 2023-06-26 10:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("enquiry", "0004_packageenquiry_order_id")]

    operations = [
        migrations.RemoveField(model_name="packageenquiry", name="order_id"),
        migrations.AddField(
            model_name="fixeddepartureenquiry",
            name="order_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
