# Generated by Django 4.1.5 on 2023-06-26 10:56

import enquiry.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("enquiry", "0005_remove_packageenquiry_order_id_and_more")]

    operations = [
        migrations.AlterField(
            model_name="fixeddepartureenquiry",
            name="order_id",
            field=models.CharField(default=enquiry.models.generate_order_id, max_length=128, unique=True),
        )
    ]
