# Generated by Django 4.0.1 on 2022-01-18 21:17

import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories", "ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "featured_image",
                    versatileimagefield.fields.VersatileImageField(upload_to="images/products/featured_image/"),
                ),
                ("summary", models.TextField()),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.category")),
            ],
            options={"ordering": ("-rank", "name")},
        ),
    ]
