# Generated by Django 4.0.2 on 2022-04-21 17:54

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("products", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
