# Generated by Django 4.2.9 on 2026-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="alt_tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
