# Generated by Django 4.2.5 on 2025-09-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_casestudy_marketingstory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casestudy",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Case Study",
                "verbose_name_plural": "Case Studies",
            },
        ),
        migrations.AlterModelOptions(
            name="marketingstory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Marketing Story",
                "verbose_name_plural": "Marketing Stories",
            },
        ),
    ]
