# Generated by Django 4.2.5 on 2025-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_casestudy_options_alter_marketingstory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("user_thumbnail", models.ImageField(upload_to="students/thumbnails/")),
                ("image", models.ImageField(upload_to="students/images/")),
                ("story", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Student Success Story",
                "verbose_name_plural": "Student Success Stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="CaseStudy",
        ),
    ]
