# Generated by Django 4.2.5 on 2025-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_studentsuccessstory_delete_casestudy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="courses/thumbnails/")),
                ("button_text", models.CharField(default="Learn More", max_length=50)),
                ("button_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["-created_at"],
            },
        ),
    ]
