# Generated by Django 4.2.9 on 2025-10-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("featured_image", models.ImageField(upload_to="blog/")),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("expertise", models.TextField()),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="mentors/"),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="mentors/logos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor",
                "verbose_name_plural": "Mentors",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="tools/")),
            ],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "ordering": ["-name"],
            },
        ),
        migrations.RenameModel(
            old_name="Partner",
            new_name="HiringPartner",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="MarketingStory",
        ),
        migrations.DeleteModel(
            name="StudentSuccessStory",
        ),
        migrations.DeleteModel(
            name="Tutor",
        ),
        migrations.AlterModelOptions(
            name="hiringpartner",
            options={
                "ordering": ["-name"],
                "verbose_name": "Hiring Partner",
                "verbose_name_plural": "Hiring Partners",
            },
        ),
    ]
