# Generated by Django 4.0.4 on 2022-05-21 21:15

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cource Category",
                "verbose_name_plural": "Cource Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                ("place", models.CharField(blank=True, max_length=120, null=True)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("photo", models.ImageField(upload_to="images/testimonials")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=120)),
                ("course", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("photo", models.ImageField(upload_to="images/testimonials")),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("logo", models.ImageField(upload_to="images/universities")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cource Category",
                "verbose_name_plural": "Cource Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("type", models.CharField(max_length=128)),
                ("duration", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.category")),
                ("university", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.university")),
            ],
            options={"ordering": ("name",)},
        ),
    ]
