# Generated by Django 4.0.4 on 2022-05-21 21:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("web", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={"ordering": ("name",), "verbose_name": "University", "verbose_name_plural": "Universities"},
        ),
        migrations.RemoveField(model_name="partner", name="photo"),
        migrations.AddField(
            model_name="partner",
            name="logo_bw",
            field=models.ImageField(default=1, upload_to="images/partners"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partner",
            name="logo_color",
            field=models.ImageField(default=1, upload_to="images/partners"),
            preserve_default=False,
        ),
    ]
