# Generated by Django 4.0.4 on 2022-05-22 07:27

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("web", "0002_alter_university_options_remove_partner_photo_and_more")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="web.category"),
        ),
        migrations.AlterField(
            model_name="course",
            name="university",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="web.university"),
        ),
    ]
