# Generated by Django 4.2.9 on 2024-03-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('products', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='order', name='zipcode'),
        migrations.AlterField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
