# Generated by Django 4.2.9 on 2024-03-18 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('web', '0004_product_video_material'), ('products', '0003_alter_order_first_name')]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                (
                    'address_line_2',
                    models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
                ),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customorder')),
                (
                    'product_option',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_items', to='web.product'
                    ),
                ),
            ],
        ),
    ]
