# Generated by Django 4.2.9 on 2024-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_customorder_customorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="file_input",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
