# Generated by Django 4.2.9 on 2025-02-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_orderitem_file_input_orderitem_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.AddField(
            model_name="cart",
            name="session_id",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
