# Generated by Django 4.2.9 on 2024-03-07 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('web', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='offer', name='discount'),
        migrations.RemoveField(model_name='product', name='regular_price'),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=1, upload_to='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(model_name='product', name='summary', field=models.TextField(blank=True, null=True)),
        migrations.AlterField(model_name='offer', name='sold_count', field=models.PositiveIntegerField(default=0)),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'is_active',
                    models.BooleanField(
                        choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active'
                    ),
                ),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='section')),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Explore', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=200, null=True)),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(app_label)s_%(class)s_creator',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections', 'ordering': ('title',)},
        ),
    ]
