# Generated by Django 4.2.9 on 2024-03-08 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_remove_offer_discount_remove_product_regular_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'is_active',
                    models.BooleanField(
                        choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='review')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('comment', models.TextField()),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(app_label)s_%(class)s_creator',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
            ],
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews', 'ordering': ('product',)},
        )
    ]
