# Generated by Django 4.2.9 on 2024-03-18 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('web', '0003_review')]

    operations = [
        migrations.AddField(
            model_name='product', name='video', field=models.FileField(blank=True, null=True, upload_to='product')
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'is_active',
                    models.BooleanField(
                        choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='material')),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(app_label)s_%(class)s_creator',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materials', 'ordering': ('name',)},
        ),
    ]
