# Generated by Django 4.2.9 on 2024-06-02 23:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_product_video_material"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="information",
            options={
                "ordering": ("title",),
                "verbose_name": "Product Information",
                "verbose_name_plural": "Product Informations",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ("title",),
                "verbose_name": "Page Section",
                "verbose_name_plural": "Page Sections",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="is_addon",
            field=models.BooleanField(default=False, verbose_name="Handle as an Addon"),
        ),
        migrations.AddField(
            model_name="product",
            name="enable_file_upload",
            field=models.BooleanField(default=False, verbose_name="Enable file upload"),
        ),
        migrations.AddField(
            model_name="product",
            name="enable_gift_wrapping",
            field=models.BooleanField(
                default=False, verbose_name="Enable gift wrapping"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="enable_greeting_card",
            field=models.BooleanField(
                default=False, verbose_name="Enable greeting card"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="enable_message",
            field=models.BooleanField(default=False, verbose_name="Enable message"),
        ),
        migrations.AddField(
            model_name="product",
            name="file_upload_label",
            field=models.CharField(
                default="Upload File", max_length=100, verbose_name="File Upload Label"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="message_label",
            field=models.CharField(
                default="Your Message", max_length=100, verbose_name="Message Label"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("MAIN", "Main Product"),
                    ("WRAP", "Gift Wrapping"),
                    ("CARD", "Greeting Card"),
                    ("ADDON", "Addons"),
                ],
                default="MAIN",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
