# Generated by Django 4.2.9 on 2024-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_information_options_alter_section_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="enable_addons",
            field=models.BooleanField(default=False, verbose_name="Enable addons"),
        ),
    ]
