# Generated by Django 4.2.9 on 2024-06-04 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_product_enable_addons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="content",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="position",
        ),
    ]
