# Generated by Django 4.2.9 on 2024-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_remove_testimonial_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_trending",
            field=models.BooleanField(default=False, verbose_name="Mark as Trending"),
        ),
    ]
