# Generated by Django 4.2.9 on 2024-08-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_product_is_trending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(),
        ),
    ]
