# Generated by Django 4.2.9 on 2024-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="link",
            field=models.CharField(
                default="https://alotgifthampers.com/products/", max_length=200
            ),
            preserve_default=False,
        ),
    ]
