# Generated by Django 4.2.9 on 2024-09-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_slider_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("show_welcome_text", models.BooleanField(default=True)),
                ("welcome_text", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "General Setting",
                "verbose_name_plural": "General Settings",
            },
        ),
    ]
