# Generated by Django 4.2.9 on 2025-07-19 08:35

import uuid

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("room_no", models.CharField(max_length=200)),
                ("floor", models.CharField(max_length=200)),
                ("building_name", models.CharField(max_length=200)),
                ("street_name", models.CharField(max_length=200)),
                ("contact_number", models.CharField(max_length=200)),
                ("address_type", models.CharField(choices=[("Home", "Home"), ("Office", "Office")], max_length=200)),
                ("location", models.URLField(blank=True, null=True, verbose_name="Location Map Link")),
                ("is_default", models.BooleanField(default=False, verbose_name="Set as default delivery address")),
            ],
            options={
                "verbose_name": "Delivery Address",
                "verbose_name_plural": "Delivery Addresses",
                "ordering": ("preference",),
            },
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Item Category",
                "verbose_name_plural": "Item Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ItemMaster",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="items/images/")),
                ("item_code", models.CharField(max_length=200, unique=True)),
                (
                    "mealtype",
                    models.CharField(
                        blank=True, choices=[("EARLY_BREAKFAST", "Early Break Fast"), ("BREAKFAST", "Break Fast"), ("LUNCH", "Lunch"), ("TIFFIN_LUNCH", "Tiffin Lunch"), ("DINNER", "Dinner")], max_length=200, null=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ("is_veg", models.BooleanField(default=True)),
                ("is_fallback", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Item Master",
                "verbose_name_plural": "Item Masters",
                "ordering": ("item_code",),
            },
        ),
        migrations.CreateModel(
            name="MealCategory",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("order", models.PositiveIntegerField(default=1)),
                ("group", models.CharField(choices=[("ESSENTIAL", "Essential"), ("REGULAR", "Regular"), ("DELUXE", "Deluxe"), ("STANDARD", "Standard")], max_length=200)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=200)),
                ("image", models.ImageField(upload_to="mealcategories/image")),
                ("description", models.TextField(blank=True, null=True)),
                ("brochure", models.FileField(blank=True, null=True, upload_to="mealcategories/brochure/")),
            ],
            options={
                "verbose_name": "Meal Category",
                "verbose_name_plural": "Meal Categories",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="MealOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("date", models.DateField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("IN_PREPERATION", "In Preparation"), ("IN_TRANSIT", "In Transit"), ("DELIVERED", "Delivered"), ("CANCELLED", "Cancelled")], default="PENDING", max_length=200
                    ),
                ),
                ("is_donated", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Meal Order",
                "verbose_name_plural": "Meal Orders",
                "ordering": ("date",),
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "day",
                    models.CharField(
                        choices=[("Monday", "Monday"), ("Tuesday", "Tuesday"), ("Wednesday", "Wednesday"), ("Thursday", "Thursday"), ("Friday", "Friday"), ("Saturday", "Saturday"), ("Sunday", "Sunday")], max_length=200
                    ),
                ),
                ("is_fallback", models.BooleanField(default=False, help_text="Day will be ignored for Fallback items (No Meal)")),
            ],
            options={
                "verbose_name": "Meal Plan",
                "verbose_name_plural": "Meal Plans",
                "ordering": ("meal_category", "day"),
            },
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("session_id", models.CharField(blank=True, max_length=200, null=True)),
                ("first_name", models.CharField(blank=True, max_length=200, null=True)),
                ("last_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("preferred_language", models.CharField(blank=True, choices=[("en", "English"), ("ml", "Malayalam"), ("ar", "Arabic"), ("hi", "Hindi"), ("ta", "Tamil"), ("te", "Telugu")], max_length=200, null=True)),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                ("alternate_mobile", models.CharField(blank=True, max_length=15, null=True)),
                ("whatsapp_number", models.CharField(blank=True, max_length=15, null=True)),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="Subscription Starts from")),
                ("notes", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=200)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("meal_fee", models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Meal Fee: PriceAfterVAT")),
                ("no_of_meals", models.PositiveIntegerField(default=0)),
                ("brand", models.CharField(default="Mess for", max_length=200)),
            ],
            options={
                "verbose_name": "Preference",
                "verbose_name_plural": "Preferences",
                "ordering": ("user",),
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ("start_date",),
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("validity", models.PositiveIntegerField(help_text="In Days")),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ("meal_category", "validity", "order"),
            },
        ),
        migrations.CreateModel(
            name="SubscriptionSubPlan",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "available_mealtypes",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[("EARLY_BREAKFAST", "Early Break Fast"), ("BREAKFAST", "Break Fast"), ("LUNCH", "Lunch"), ("TIFFIN_LUNCH", "Tiffin Lunch"), ("DINNER", "Dinner")], max_length=200
                    ),
                ),
                ("plan_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Sub Plan",
                "verbose_name_plural": "Sub Plans",
                "ordering": ("order",),
            },
        ),
    ]
