# Generated by Django 4.2.9 on 2025-07-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="meal_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Meal Fee: PriceAfterVAT"),
        ),
    ]
