# Generated by Django 4.2.9 on 2025-08-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_preference_meal_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Subscription Ends on"),
        ),
    ]
