# Generated by Django 4.2.9 on 2025-08-05 16:50

import uuid

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_preference_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="brand",
        ),
        migrations.AddField(
            model_name="preference",
            name="included_days",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("Monday", "Monday"), ("Tuesday", "Tuesday"), ("Wednesday", "Wednesday"), ("Thursday", "Thursday"), ("Friday", "Friday"), ("Saturday", "Saturday"), ("Sunday", "Sunday")],
                help_text="Select days to include for meal delivery",
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("creator", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
