# Generated by Django 4.2.9 on 2025-08-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_preference_brand_preference_included_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="brand",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="main.brand", verbose_name=""),
        ),
    ]
