# Generated by Django 4.2.9 on 2025-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_preference_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="included_days",
        ),
        migrations.AddField(
            model_name="preference",
            name="friday_selected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="monday_selected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="saturday_selected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="sunday_selected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="thursday_selected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="tuesday_selected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="wednesday_selected",
            field=models.BooleanField(default=True),
        ),
    ]
