# Generated by Django 4.2.9 on 2025-08-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_preference_included_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="breakfast_delivery_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("08:00-08:30", "8:00 AM - 8:30 AM"),
                    ("08:30-09:00", "8:30 AM - 9:00 AM"),
                    ("09:00-09:30", "9:00 AM - 9:30 AM"),
                    ("09:30-10:00", "9:30 AM - 10:00 AM"),
                    ("10:00-10:30", "10:00 AM - 10:30 AM"),
                    ("10:30-11:00", "10:30 AM - 11:00 AM"),
                ],
                help_text="Select delivery time for breakfast (8:00 AM - 11:00 AM)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="dinner_delivery_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("18:00-18:30", "6:00 PM - 6:30 PM"),
                    ("18:30-19:00", "6:30 PM - 7:00 PM"),
                    ("19:00-19:30", "7:00 PM - 7:30 PM"),
                    ("19:30-20:00", "7:30 PM - 8:00 PM"),
                    ("20:00-20:30", "8:00 PM - 8:30 PM"),
                    ("20:30-21:00", "8:30 PM - 9:00 PM"),
                ],
                help_text="Select delivery time for dinner (6:00 PM - 9:00 PM)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="early_breakfast_delivery_time",
            field=models.CharField(
                blank=True, choices=[("07:00-07:30", "7:00 AM - 7:30 AM"), ("07:30-08:00", "7:30 AM - 8:00 AM")], help_text="Select delivery time for early breakfast (7:00 AM - 8:00 AM)", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="lunch_delivery_time",
            field=models.CharField(
                blank=True,
                choices=[("12:00-12:30", "12:00 PM - 12:30 PM"), ("12:30-13:00", "12:30 PM - 1:00 PM"), ("13:00-13:30", "1:00 PM - 1:30 PM"), ("13:30-14:00", "1:30 PM - 2:00 PM")],
                help_text="Select delivery time for lunch (12:00 PM - 2:00 PM)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="tiffin_lunch_delivery_time",
            field=models.CharField(
                blank=True,
                choices=[("12:00-12:30", "12:00 PM - 12:30 PM"), ("12:30-13:00", "12:30 PM - 1:00 PM"), ("13:00-13:30", "1:00 PM - 1:30 PM"), ("13:30-14:00", "1:30 PM - 2:00 PM")],
                help_text="Select delivery time for tiffin lunch (12:00 PM - 2:00 PM)",
                max_length=20,
                null=True,
            ),
        ),
    ]
