# Generated by Django 4.2.9 on 2025-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_preference_dinner_delivery_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="dinner_delivery_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("19:00-19:30", "7:00 PM - 7:30 PM"),
                    ("19:30-20:00", "7:30 PM - 8:00 PM"),
                    ("20:00-20:30", "8:00 PM - 8:30 PM"),
                    ("20:30-21:00", "8:30 PM - 9:00 PM"),
                    ("21:00-21:30", "9:00 PM - 9:30 PM"),
                    ("21:30-22:00", "9:30 PM - 10:00 PM"),
                ],
                help_text="Select delivery time for dinner (7:00 PM - 10:00 PM)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="lunch_delivery_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("12:00-12:30", "12:00 PM - 12:30 PM"),
                    ("12:30-13:00", "12:30 PM - 1:00 PM"),
                    ("13:00-13:30", "1:00 PM - 1:30 PM"),
                    ("13:30-14:00", "1:30 PM - 2:00 PM"),
                    ("14:00-14:30", "2:00 PM - 2:30 PM"),
                    ("14:30-15:00", "2:30 PM - 3:00 PM"),
                ],
                help_text="Select delivery time for lunch (12:00 PM - 3:00 PM)",
                max_length=20,
                null=True,
            ),
        ),
    ]
