# Generated by Django 4.2.9 on 2025-09-21 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_preference_dinner_delivery_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmaster",
            name="item_code",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mealcategory",
            name="group",
            field=models.CharField(
                choices=[
                    ("ESSENTIAL", "Essential"),
                    ("REGULAR", "Regular"),
                    ("DELUXE", "Deluxe"),
                    ("STANDARD", "Standard"),
                    ("MESS FOR LESS", "Mess for Less"),
                    ("PATHU'S KITCHEN", "Pathu's Kitchen"),
                    ("CHECHI'S KITCHEN", "Chechi's Kitchen"),
                    ("PRIME", "Prime"),
                    ("SAVER", "Saver"),
                    ("CLASSIC", "Classic"),
                    ("PREMIUM", "Premium"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="brand",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.brand", verbose_name=""),
        ),
    ]
