# Generated by Django 4.2.9 on 2025-09-23 14:42

from django.db import migrations
from django.utils.text import slugify


def populate_groups(apps, schema_editor):
    """Populate Group table with existing group choices"""
    Group = apps.get_model('main', 'Group')
    
    # Define the group choices from the original choices.py
    GROUP_CHOICES = [
        ("ESSENTIAL", "Essential"),
        ("REGULAR", "Regular"),
        ("DELUXE", "Deluxe"),
        ("STANDARD", "Standard"),
        ("MESS FOR LESS", "Mess for Less"),
        ("PATHU'S KITCHEN", "Pathu's Kitchen"),
        ("CHECHI'S KITCHEN", "Chechi's Kitchen"),
        ("PRIME", "Prime"),
        ("SAVER", "Saver"),
        ("CLASSIC", "Classic"),
        ("PREMIUM", "Premium"),
    ]
    
    # Create Group objects
    for order, (code, name) in enumerate(GROUP_CHOICES, 1):
        Group.objects.get_or_create(
            name=name,
            defaults={
                'slug': slugify(name),
                'order': order,
                'is_active': True
            }
        )


def reverse_populate_groups(apps, schema_editor):
    """Reverse the population - delete all groups"""
    Group = apps.get_model('main', 'Group')
    Group.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_group_model_only'),
    ]

    operations = [
        migrations.RunPython(populate_groups, reverse_populate_groups),
    ]
