# Generated by Django 4.2.9 on 2025-09-23 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_populate_groups'),
    ]

    operations = [
        # Add the new group_fk field
        migrations.AddField(
            model_name='mealcategory',
            name='group_fk',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_categories_fk', to='main.group'),
        ),
    ]
