# Generated by Django 4.2.9 on 2025-09-23 16:31

from django.db import migrations


def populate_group_fk(apps, schema_editor):
    """Populate group_fk field in MealCategory based on existing group string values"""
    Group = apps.get_model('main', 'Group')
    MealCategory = apps.get_model('main', 'MealCategory')
    
    # Create mapping from group string values to Group objects
    group_mapping = {}
    for group in Group.objects.all():
        # Map the original string values to Group objects
        if group.name == "Essential":
            group_mapping["ESSENTIAL"] = group
        elif group.name == "Regular":
            group_mapping["REGULAR"] = group
        elif group.name == "Deluxe":
            group_mapping["DELUXE"] = group
        elif group.name == "Standard":
            group_mapping["STANDARD"] = group
        elif group.name == "Mess for Less":
            group_mapping["MESS FOR LESS"] = group
        elif group.name == "Pathu's Kitchen":
            group_mapping["PATHU'S KITCHEN"] = group
        elif group.name == "Chechi's Kitchen":
            group_mapping["CHECHI'S KITCHEN"] = group
        elif group.name == "Prime":
            group_mapping["PRIME"] = group
        elif group.name == "Saver":
            group_mapping["SAVER"] = group
        elif group.name == "Classic":
            group_mapping["CLASSIC"] = group
        elif group.name == "Premium":
            group_mapping["PREMIUM"] = group
    
    # Update MealCategory records to set group_fk
    for meal_category in MealCategory.objects.all():
        if meal_category.group in group_mapping:
            meal_category.group_fk = group_mapping[meal_category.group]
            meal_category.save()


def reverse_populate_group_fk(apps, schema_editor):
    """Reverse the population - clear group_fk field"""
    MealCategory = apps.get_model('main', 'MealCategory')
    MealCategory.objects.all().update(group_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add_group_fk_to_mealcategory'),
    ]

    operations = [
        migrations.RunPython(populate_group_fk, reverse_populate_group_fk),
    ]
