# Generated by Django 4.2.9 on 2025-09-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_populate_group_fk'),
    ]

    operations = [
        # Remove the old group field
        migrations.RemoveField(
            model_name='mealcategory',
            name='group',
        ),
        # Rename group_fk to group
        migrations.RenameField(
            model_name='mealcategory',
            old_name='group_fk',
            new_name='group',
        ),
        # Make the field non-nullable
        migrations.AlterField(
            model_name='mealcategory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_categories', to='main.group'),
        ),
    ]
