# Generated by Django 4.2.9 on 2025-09-24 09:11

from django.db import migrations, models
import django.db.models.deletion


def create_brands_and_assign_to_groups(apps, schema_editor):
    """Create brands and assign them to appropriate groups"""
    Brand = apps.get_model('main', 'Brand')
    Group = apps.get_model('main', 'Group')
    
    # Create brands
    alot_kitchen, _ = Brand.objects.get_or_create(name="Alot Kitchen")
    mess_for_less, _ = Brand.objects.get_or_create(name="Mess for Less")
    chechi_kitchen, _ = Brand.objects.get_or_create(name="Chechi Kitchen")
    pathu_kitchen, _ = Brand.objects.get_or_create(name="Pathu Kitchen")
    
    # Assign brands to groups
    # Alot Kitchen brand groups
    alot_groups = ['Prime', 'Saver', 'Classic', 'Premium', 'Essential', 'Regular', 'Deluxe', 'Standard']
    for group_name in alot_groups:
        try:
            group = Group.objects.get(name=group_name)
            group.brand = alot_kitchen
            group.save()
        except Group.DoesNotExist:
            print(f"Group {group_name} does not exist")
    
    # Mess for Less brand groups
    try:
        mess_group = Group.objects.get(name="Mess for Less")
        mess_group.brand = mess_for_less
        mess_group.save()
    except Group.DoesNotExist:
        print(f"Group Mess for Less does not exist")
    
    # Chechi Kitchen brand groups
    try:
        chechi_group = Group.objects.get(name="Chechi's Kitchen")
        chechi_group.brand = chechi_kitchen
        chechi_group.save()
    except Group.DoesNotExist:
        print(f"Group Chechi's Kitchen does not exist")
    
    # Pathu Kitchen brand groups
    try:
        pathu_group = Group.objects.get(name="Pathu's Kitchen")
        pathu_group.brand = pathu_kitchen
        pathu_group.save()
    except Group.DoesNotExist:
        print(f"Group Pathu's Kitchen does not exist")


def reverse_create_brands_and_assign_to_groups(apps, schema_editor):
    """Reverse the brand assignment"""
    Group = apps.get_model('main', 'Group')
    Group.objects.all().update(brand=None)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_finalize_group_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.brand'),
        ),
        migrations.RunPython(create_brands_and_assign_to_groups, reverse_create_brands_and_assign_to_groups),
    ]
