# Generated by Django 4.2.9 on 2025-09-24 09:14

from django.db import migrations, models
import django.db.models.deletion


def ensure_all_groups_have_brands(apps, schema_editor):
    """Ensure all groups have brands assigned before making field non-nullable"""
    Brand = apps.get_model('main', 'Brand')
    Group = apps.get_model('main', 'Group')
    
    # Get or create a default brand for any groups without brands
    default_brand, _ = Brand.objects.get_or_create(name="Alot Kitchen")
    
    # Assign default brand to any groups that don't have a brand
    groups_without_brands = Group.objects.filter(brand__isnull=True)
    for group in groups_without_brands:
        group.brand = default_brand
        group.save()


def reverse_ensure_all_groups_have_brands(apps, schema_editor):
    """Reverse function - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_brands_and_assign_to_groups'),
    ]

    operations = [
        migrations.RunPython(ensure_all_groups_have_brands, reverse_ensure_all_groups_have_brands),
        migrations.AlterField(
            model_name='group',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.brand'),
        ),
    ]
