# Generated by Django 4.2.9 on 2025-09-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='brand',
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='sap_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
