# Generated by Django 4.2.9 on 2025-09-25 15:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_preference_brand_mealcategory_sap_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='early_breakfast_address',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='early_breakfast_delivery_time',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='friday_early_breakfast',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='monday_early_breakfast',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='saturday_early_breakfast',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='sunday_early_breakfast',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='thursday_early_breakfast',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='tuesday_early_breakfast',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='wednesday_early_breakfast',
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='mealtype',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Break Fast'), ('LUNCH', 'Lunch'), ('TIFFIN_LUNCH', 'Tiffin Lunch'), ('DINNER', 'Dinner')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionsubplan',
            name='available_mealtypes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BREAKFAST', 'Break Fast'), ('LUNCH', 'Lunch'), ('TIFFIN_LUNCH', 'Tiffin Lunch'), ('DINNER', 'Dinner')], max_length=200),
        ),
    ]
