# Generated by Django 4.2.9 on 2025-09-27 16:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_preference_early_breakfast_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='mealtype',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Break Fast'), ('LUNCH', 'Lunch'), ('TIFFIN_LUNCH', 'Tiffin Lunch'), ('DESI TIFFIN LUNCH', 'Desi Tiffin Lunch'), ('DINNER', 'Dinner')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionsubplan',
            name='available_mealtypes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BREAKFAST', 'Break Fast'), ('LUNCH', 'Lunch'), ('TIFFIN_LUNCH', 'Tiffin Lunch'), ('DESI TIFFIN LUNCH', 'Desi Tiffin Lunch'), ('DINNER', 'Dinner')], max_length=200),
        ),
    ]
