# Generated by Django 4.2.9 on 2025-10-08 14:38

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_itemmaster_mealtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='desi_tiffin_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desi_tiffin_address', to='main.deliveryaddress'),
        ),
        migrations.AddField(
            model_name='preference',
            name='desi_tiffin_delivery_time',
            field=models.CharField(blank=True, choices=[('08:00-08:30', '8:00 AM - 8:30 AM'), ('08:30-09:00', '8:30 AM - 9:00 AM'), ('09:00-09:30', '9:00 AM - 9:30 AM'), ('09:30-10:00', '9:30 AM - 10:00 AM'), ('10:00-10:30', '10:00 AM - 10:30 AM'), ('10:30-11:00', '10:30 AM - 11:00 AM')], help_text='Select delivery time for desi tiffin (8:00 AM - 11:00 AM)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='friday_desi_tiffin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('day', 'Friday'), ('menu_item__mealtype', 'DESI_TIFFIN')), ('is_fallback', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday_desi_tiffin', to='main.mealplan'),
        ),
        migrations.AddField(
            model_name='preference',
            name='monday_desi_tiffin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('day', 'Monday'), ('menu_item__mealtype', 'DESI_TIFFIN')), ('is_fallback', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday_desi_tiffin', to='main.mealplan'),
        ),
        migrations.AddField(
            model_name='preference',
            name='saturday_desi_tiffin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('day', 'Saturday'), ('menu_item__mealtype', 'DESI_TIFFIN')), ('is_fallback', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_desi_tiffin', to='main.mealplan'),
        ),
        migrations.AddField(
            model_name='preference',
            name='sunday_desi_tiffin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('day', 'Sunday'), ('menu_item__mealtype', 'DESI_TIFFIN')), ('is_fallback', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_desi_tiffin', to='main.mealplan'),
        ),
        migrations.AddField(
            model_name='preference',
            name='thursday_desi_tiffin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('day', 'Thursday'), ('menu_item__mealtype', 'DESI_TIFFIN')), ('is_fallback', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_desi_tiffin', to='main.mealplan'),
        ),
        migrations.AddField(
            model_name='preference',
            name='tuesday_desi_tiffin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('day', 'Tuesday'), ('menu_item__mealtype', 'DESI_TIFFIN')), ('is_fallback', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_desi_tiffin', to='main.mealplan'),
        ),
        migrations.AddField(
            model_name='preference',
            name='wednesday_desi_tiffin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('day', 'Wednesday'), ('menu_item__mealtype', 'DESI_TIFFIN')), ('is_fallback', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_desi_tiffin', to='main.mealplan'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='mealtype',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Break Fast'), ('DESI_TIFFIN', 'Desi Tiffin'), ('LUNCH', 'Lunch'), ('TIFFIN_LUNCH', 'Tiffin Lunch'), ('DINNER', 'Dinner')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionsubplan',
            name='available_mealtypes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BREAKFAST', 'Break Fast'), ('DESI_TIFFIN', 'Desi Tiffin'), ('LUNCH', 'Lunch'), ('TIFFIN_LUNCH', 'Tiffin Lunch'), ('DINNER', 'Dinner')], max_length=200),
        ),
    ]
