# Generated by Django 4.2.9 on 2025-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_add_desi_tiffin_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='tiffin_lunch_delivery_time',
            field=models.CharField(blank=True, choices=[('08:00-08:30', '8:00 AM - 8:30 AM'), ('08:30-09:00', '8:30 AM - 9:00 AM'), ('09:00-09:30', '9:00 AM - 9:30 AM'), ('09:30-10:00', '9:30 AM - 10:00 AM'), ('10:00-10:30', '10:00 AM - 10:30 AM'), ('10:30-11:00', '10:30 AM - 11:00 AM')], help_text='Select delivery time for tiffin lunch (8:00 AM - 11:00 AM)', max_length=20, null=True),
        ),
    ]
