# Generated by Django 4.2.5 on 2025-10-07 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="district",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="zones", to="main.district"),
        ),
        migrations.AddField(
            model_name="district",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"usertype": "DistrictConvenor"}, on_delete=django.db.models.deletion.CASCADE, related_name="districts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
