# Generated by Django 4.2.5 on 2025-10-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_company_payable_receivable_transaction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("title",), "verbose_name": "Transaction", "verbose_name_plural": "Transactions"},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="main.transactioncategory"),
        ),
    ]
