# Generated by Django 4.2.5 on 2025-10-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_transaction_options_alter_transaction_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payable",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="receivable",
            name="due_date",
        ),
        migrations.AlterField(
            model_name="payable",
            name="date",
            field=models.DateField(verbose_name="Due Date"),
        ),
        migrations.AlterField(
            model_name="receivable",
            name="date",
            field=models.DateField(verbose_name="Due Date"),
        ),
    ]
