# Generated by Django 4.2.9 on 2024-02-14 19:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='career/', verbose_name='Image')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
            ],
            options={'verbose_name': 'Career', 'verbose_name_plural': 'Careers'},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Image')),
            ],
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
