# Generated by Django 4.2.9 on 2024-02-14 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [('web', '0002_career_team')]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        )
    ]
