# Generated by Django 4.2.9 on 2024-02-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0003_news_date')]

    operations = [
        migrations.AlterModelOptions(
            name='slider', options={'ordering': ['order'], 'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'}
        ),
        migrations.AddField(
            model_name='slider', name='order', field=models.PositiveIntegerField(default=0, verbose_name='Order')
        ),
    ]
