# Generated by Django 4.2.9 on 2024-02-18 12:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [('web', '0004_alter_slider_options_slider_order')]

    operations = [
        migrations.RemoveField(model_name='career', name='content'),
        migrations.RemoveField(model_name='career', name='image'),
        migrations.AlterField(
            model_name='news', name='content', field=tinymce.models.HTMLField(verbose_name='Content')
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('qualification', models.CharField(max_length=100, verbose_name='Qualification')),
                ('experience', models.CharField(max_length=100, verbose_name='Work Experience')),
                ('cover_letter', models.TextField(verbose_name='Cover Letter')),
                ('resume', models.FileField(upload_to='application/', verbose_name='Resume')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.career')),
            ],
            options={'verbose_name': 'Career Application', 'verbose_name_plural': 'Career Applications'},
        ),
    ]
