# Generated by Django 4.2.9 on 2024-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0005_remove_career_content_remove_career_image_and_more')]

    operations = [
        migrations.RemoveField(model_name='application', name='career'),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(default=1, max_length=180, verbose_name='Nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.CharField(default=1, max_length=180, verbose_name='Position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.CharField(max_length=180, verbose_name='Work Experience'),
        ),
        migrations.AlterField(
            model_name='application', name='fullname', field=models.CharField(max_length=180, verbose_name='Name')
        ),
        migrations.AlterField(
            model_name='application',
            name='qualification',
            field=models.CharField(max_length=180, verbose_name='Qualification'),
        ),
    ]
