# Generated by Django 4.2.9 on 2024-02-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0006_remove_application_career_application_nationality_and_more')]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country_code',
            field=models.CharField(default=1, max_length=5, verbose_name='Country Code'),
            preserve_default=False,
        )
    ]
