# Generated by Django 4.2.9 on 2024-02-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0007_application_country_code')]

    operations = [
        migrations.RemoveField(model_name='application', name='cover_letter'),
        migrations.AlterField(
            model_name='application', name='phone', field=models.CharField(max_length=20, verbose_name='Mobile')
        ),
    ]
