# Generated by Django 4.2.9 on 2024-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0008_remove_application_cover_letter_and_more')]

    operations = [
        migrations.AlterField(
            model_name='application', name='position', field=models.CharField(max_length=180, verbose_name='Job Title')
        )
    ]
