# Generated by Django 4.2.9 on 2024-02-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0009_alter_application_position')]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='brand')),
            ],
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        )
    ]
