# Generated by Django 4.2.9 on 2024-02-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0010_brand')]

    operations = [
        migrations.AlterModelOptions(
            name='brand', options={'ordering': ('order',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'}
        ),
        migrations.AddField(model_name='brand', name='order', field=models.PositiveIntegerField(default=0)),
    ]
