# Generated by Django 4.2.9 on 2024-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0011_alter_brand_options_brand_order')]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category', name='order', field=models.PositiveIntegerField(default=0, verbose_name='Order')
        ),
    ]
