# Generated by Django 4.2.9 on 2025-02-17 20:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="platform",
            options={"ordering": ["order"], "verbose_name": "Platform/Product", "verbose_name_plural": "Platforms/Products"},
        ),
        migrations.AddField(
            model_name="platform",
            name="description",
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="platforms"),
        ),
        migrations.AddField(
            model_name="platform",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
