# Generated by Django 4.2.9 on 2025-02-17 20:46

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_platform_options_platform_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotlightCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Spotlight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="spotlights")),
                ("description", tinymce.models.HTMLField()),
                ("date", models.DateField()),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.spotlightcategory")),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
