# Generated by Django 4.2.9 on 2025-02-18 02:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_spotlightcategory_spotlight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("job_id", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("description", tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name="platform",
            name="slug",
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spotlight",
            name="slug",
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
