# Generated by Django 4.2.9 on 2025-02-18 11:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_career_platform_slug_spotlight_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="frames")),
                ("page_link", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Frame",
                "verbose_name_plural": "Frames",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="partners")),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("quote", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.AlterModelOptions(
            name="career",
            options={"verbose_name": "Career", "verbose_name_plural": "Careers"},
        ),
        migrations.AlterModelOptions(
            name="spotlight",
            options={"ordering": ["date"], "verbose_name": "Spotlight", "verbose_name_plural": "Spotlights"},
        ),
        migrations.AlterModelOptions(
            name="spotlightcategory",
            options={"verbose_name": "Spotlight Category", "verbose_name_plural": "Spotlight Categories"},
        ),
        migrations.RemoveField(
            model_name="platform",
            name="image",
        ),
        migrations.AddField(
            model_name="platform",
            name="background_image",
            field=models.ImageField(default=1, upload_to="platforms"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="established_image",
            field=models.ImageField(default=1, upload_to="platforms"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="feature_image",
            field=models.ImageField(default=1, upload_to="platforms"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="summary",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="transparent_image",
            field=models.ImageField(default=1, upload_to="platforms"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="platform",
            name="description",
            field=models.TextField(),
        ),
    ]
