# Generated by Django 4.2.9 on 2025-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_contact_faq_frame_partner_testimonial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("tagline", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="companies")),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
