# Generated by Django 4.2.9 on 2025-03-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("focus", models.TextField()),
                ("responsibilities", models.TextField()),
            ],
            options={
                "verbose_name": "Committee",
                "verbose_name_plural": "Committees",
            },
        ),
        migrations.CreateModel(
            name="PlatformService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Platform Service",
                "verbose_name_plural": "Platform Services",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="team")),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.AddField(
            model_name="frame",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platform",
            name="mission",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platform",
            name="vision",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platformservice",
            name="platform",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.platform"),
        ),
    ]
