# Generated by Django 4.2.9 on 2025-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_committee_platformservice_team_delete_company_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testimonial",
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={"verbose_name": "Firm", "verbose_name_plural": "Firms"},
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(upload_to="firms"),
        ),
    ]
