# Generated by Django 4.2.9 on 2024-02-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='team')),
            ],
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        )
    ]
