# Generated by Django 4.2.9 on 2024-03-23 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('web', '0002_team')]

    operations = [migrations.RemoveField(model_name='portfolio', name='description')]
