# Generated by Django 4.2.9 on 2024-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0003_remove_portfolio_description')]

    operations = [
        migrations.RemoveField(model_name='banner', name='sub_head'),
        migrations.AddField(model_name='portfolio', name='description', field=models.TextField(blank=True, null=True)),
    ]
