# Generated by Django 4.2.9 on 2024-06-02 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('web', '0004_remove_banner_sub_head_portfolio_description')]

    operations = [migrations.DeleteModel(name='Gallery')]
