# Generated by Django 4.2.9 on 2024-08-04 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('web', '0005_delete_gallery')]

    operations = [
        migrations.RemoveField(model_name='contact', name='email'),
        migrations.RemoveField(model_name='contact', name='subject'),
    ]
