# Generated by Django 4.2.9 on 2026-03-25 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_testimonial_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_info', to='web.product')),
            ],
            options={
                'verbose_name': 'Featured Product',
                'verbose_name_plural': 'Featured Products',
                'ordering': ['order'],
            },
        ),
    ]
