# Generated by Django 4.2.9 on 2026-03-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('web', '0004_remove_product_is_featured_featuredproduct')]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='One feature per line', null=True),
        ),
        migrations.AddField(
            model_name='product', name='slug', field=models.SlugField(blank=True, null=True, unique=True)
        ),
        migrations.AddField(
            model_name='product', name='tagline', field=models.CharField(blank=True, max_length=255, null=True)
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(help_text='One ingredient per line')),
                ('instructions', models.TextField(help_text='One step per line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('prep_time', models.CharField(blank=True, max_length=50, null=True)),
                ('cook_time', models.CharField(blank=True, max_length=50, null=True)),
                ('servings', models.CharField(blank=True, max_length=50, null=True)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='web.product'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.product'
                    ),
                ),
            ],
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images', 'ordering': ['order']},
        ),
    ]
