# Generated by Django 4.2.9 on 2026-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('web', '0005_product_features_product_slug_product_tagline_recipe_and_more')]

    operations = [
        migrations.RemoveField(model_name='featuredproduct', name='product'),
        migrations.AddField(
            model_name='featuredproduct',
            name='image',
            field=models.ImageField(default=1, upload_to='featured_products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredproduct',
            name='product_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
