# Generated by Django 4.0.5 on 2022-11-13 18:34

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="property")),
                ("map_src", models.CharField(blank=True, max_length=400, null=True)),
                ("video_id", models.CharField(blank=True, max_length=200, null=True)),
                ("listed_on", models.DateField(auto_now_add=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("property_id", models.CharField(blank=True, max_length=200, null=True)),
                ("property_type", models.CharField(blank=True, max_length=200, null=True)),
                ("property_status", models.CharField(blank=True, max_length=200, null=True)),
                ("property_price", models.CharField(blank=True, max_length=200, null=True)),
                ("property_area", models.CharField(blank=True, max_length=200, null=True)),
                ("property_bedrooms", models.CharField(blank=True, max_length=200, null=True)),
                ("property_bathrooms", models.CharField(blank=True, max_length=200, null=True)),
                ("property_garages", models.CharField(blank=True, max_length=200, null=True)),
                ("property_year_built", models.CharField(blank=True, max_length=200, null=True)),
                ("property_floor", models.CharField(blank=True, max_length=200, null=True)),
                ("amenities", models.ManyToManyField(related_name="properties", to="app.amenity")),
            ],
            options={"verbose_name_plural": "Properties"},
        ),
        migrations.CreateModel(
            name="Realtor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("photo", models.ImageField(upload_to="realtors")),
                ("designation", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="property")),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.property")),
            ],
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feature", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.property")),
            ],
        ),
    ]
