# Generated by Django 4.0.1 on 2022-01-18 21:16

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="About Fadhil Mohammed", max_length=128),
                ),
                ("content", models.TextField()),
                ("mission", models.TextField()),
                ("vision", models.TextField()),
                ("dreams", models.TextField()),
                (
                    "email",
                    models.EmailField(
                        default="hello@fadhilmohammed.com", max_length=254
                    ),
                ),
            ],
            options={"verbose_name": "About", "verbose_name_plural": "About"},
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("content", models.TextField()),
                (
                    "logo",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/clients"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="images/news"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "News", "verbose_name_plural": "Newses"},
        ),
    ]
