# Generated by Django 4.0.1 on 2022-01-18 21:19

import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("", "-- Select Team --"),
                            ("Chairman", "Chairman"),
                            ("Managing-Director", "Managing-Director"),
                            ("Operation-Manager", "Operation-Manager"),
                        ],
                        max_length=128,
                    ),
                ),
                ("message", models.TextField()),
            ],
            options={"verbose_name": "Appointment Request", "verbose_name_plural": "Appointment Requests"},
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("department", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=120)),
                ("photo", versatileimagefield.fields.VersatileImageField(upload_to="images/leadership")),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20, verbose_name="Image PPOI"
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Job Post", "verbose_name_plural": "Job Posts"},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("photo", versatileimagefield.fields.VersatileImageField(upload_to="images/news")),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20, verbose_name="Image PPOI"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                ("message", models.TextField()),
            ],
            options={"verbose_name": "Contact Form Entry", "verbose_name_plural": "Contact Form Entries"},
        ),
        migrations.CreateModel(
            name="Leadership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("designation", models.CharField(max_length=120)),
                ("photo", versatileimagefield.fields.VersatileImageField(upload_to="images/leadership")),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20, verbose_name="Image PPOI"
                    ),
                ),
                ("description", models.TextField()),
                ("order", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("order",)},
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("photo", versatileimagefield.fields.VersatileImageField(upload_to="images/news")),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20, verbose_name="Image PPOI"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("summary", models.TextField()),
                ("content", tinymce.models.HTMLField()),
                ("show_in_homepage", models.BooleanField(default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.category")),
            ],
            options={"verbose_name": "News & Updates", "verbose_name_plural": "Newses & Updates"},
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
            ],
            options={"verbose_name": "Project Category", "verbose_name_plural": "Project Categories"},
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("designation", models.CharField(max_length=120)),
                ("photo", versatileimagefield.fields.VersatileImageField(upload_to="images/teams")),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20, verbose_name="Image PPOI"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("order",)},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "COMPLETED"), ("ONGOING", "ONGOING")],
                        default="COMPLETED",
                        max_length=128,
                    ),
                ),
                ("photo", versatileimagefield.fields.VersatileImageField(upload_to="images/projects")),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20, verbose_name="Image PPOI"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.category")),
            ],
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("photo", versatileimagefield.fields.VersatileImageField(upload_to="images/leadership")),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20, verbose_name="Image PPOI"
                    ),
                ),
                ("news", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.news")),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=120)),
                ("resume", models.FileField(upload_to="")),
                ("career", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.career")),
            ],
            options={"verbose_name": "Job Application", "verbose_name_plural": "Job Applications"},
        ),
    ]
